### ISSUE TITLE
Unable to connect to Application instance: Element not found

### ISSUE THREAD

**Issue by JPLost** [IronLanguages/ironpython2#614]
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description
I'm using IronPython 2.7.9 on Visual Studio Community Edition 2017 15.9.11 building a Ironpython WPF application.
I'm trying to connect to Solidworks 2016 SP5.0 Application and get and pass data between the independent program and Solidworks. First step was to get the title of the active document on program.

### Steps to Reproduce
Using code:
import clr
import sys
import System

t = System.Type.GetTypeFromProgID("SldWorks.Application")
swApp = System.Activator.CreateInstance(t)

doc = swApp.ActiveDoc
print(doc.GetTitle())

**Expected behavior:** 

Running through Visual Studio 2017 interactive window, it should show 
Bush.SLDPRT

**Actual behavior:** [What actually happened]
Running code on interactive window:
>>> doc = swApp.ActiveDoc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
EnvironmentError: System.Runtime.InteropServices.COMException (0x8002802B): Elementtiä ei löydy. (HRESULT-poikkeus: 0x8002802B (TYPE_E_ELEMENTNOTFOUND))
   kohteessa System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   kohteessa Microsoft.Scripting.ComInterop.ComRuntimeHelpers.GetITypeInfoFromIDispatch(IDispatch dispatch, Boolean throwIfMissingExpectedTypeInfo)
   kohteessa Microsoft.Scripting.ComInterop.IDispatchComObject.EnsureScanDefinedMethods()
   kohteessa Microsoft.Scripting.ComInterop.IDispatchComObject.System.Dynamic.IDynamicMetaObjectProvider.GetMetaObject(Expression parameter)
   kohteessa System.Dynamic.DynamicMetaObject.Create(Object value, Expression expression)
   kohteessa System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   kohteessa System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   kohteessa System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   kohteessa System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   kohteessa Microsoft.Scripting.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   kohteessa System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   kohteessa Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   kohteessa IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   kohteessa Microsoft.Scripting.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   kohteessa System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   kohteessa Microsoft.Scripting.Interpreter.FuncCallInstruction`6.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   kohteessa IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   kohteessa IronPython.Runtime.Method.MethodBinding.SelfTarget(CallSite site, CodeContext context, Object target)
   kohteessa Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   kohteessa Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)

### Versions

You can get this information from executing `ipy -V`.

**Comment by slide** [comment]
Does this work in CPython using pywin32?

**Comment by JPLost** [comment]
If I understand correctly, the CPython is what you can get from www.python.org?
I can confirm that the code works on Python 3.7.2 with pywin32 version 224
using following code:

from win32com.client import Dispatch
swApp = Dispatch('SldWorks.Application.24')
doc = swApp.ActiveDoc
print(doc.GetTitle)

**Comment by slide** [comment]
Don't you need to do the following then?

```
swApp = System.Type.GetTypeFromProgID("SldWorks.Application.24")
```

**Comment by JPLost** [comment]
Throws an error:
<>>> import clr
>>> import sys
>>> import System
>>> swApp = System.Type.GetTypeFromProgID("SldWorks.Application")
>>> doc = swApp.ActiveDoc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'RuntimeType' object has no attribute 'ActiveDoc'
>>> print(doc.GetTitle())
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'doc' is not defined>

Solidworks API is not quite forthcoming on the solution.
http://help.solidworks.com/2016/english/api/sldworksapiprogguide/GettingStarted/Understanding_the_SolidWorks_API_Class_Hierarchy.htm?id=270a7715e0e94b9083065acd994a781d#Pg0

**Comment by slide** [comment]
You are still missing the .24 in the progid. 

```
swApp = System.Type.GetTypeFromProgID("SldWorks.Application.24")
```

**Comment by slide** [comment]
Also, I would expect that you need to do the following:

```
import clr
import System
SldWorks = System.Type.GetTypeFromProgID("SldWorks.Application.24")
swApp = SldWorks()
doc = swApp.ActiveDoc
print(doc.GetTitle())
```

**Comment by JPLost** [comment]
Now we're getting something:
<
>>> import clr
>>> import System
>>> SldWorks = System.Type.GetTypeFromProgID("SldWorks.Application.24")
>>> swApp = SldWorks()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: Indeksi oli sallitun alueen ulkopuolella. Indeksi ei saa olla negatiivinen, ja sen on oltava kokoelmaa pienempi.
Parametrin nimi: index
>>> doc = swApp.ActiveDoc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'swApp' is not defined
>>> print(doc.GetTitle())
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'doc' is not defined
>>> 
>
I'll translate: "ValueError: Index is outside of allowed "range". Index can't be (is not allowed) negative and it has to be smaller than "collection"

**Comment by slide** [comment]
It's possible that there is a parameter expected or something, I am not sure. You can do a help on SldWorks after assigning and see if there is anything helpful there. I don't think this is a bug in IronPython at all. So, perhaps moving the discussion to the mailing list would be better.
